feat: print version on evse session startup
SwitchEV/pyslac pull request #34
Opened 2022-09-20 07:47 UTC by mdwcrft

Print the version from __init__ on the startup of a new `SlacEvseSession` and add a test that this matches the toml file

2022-09-20 10:29 UTC, tropxy requested changes, later dismissed

2022-09-20 10:29 UTC, tropxy commented on pyslac/session.py
> +        )
the SlacEvseSession is not good place for this, because it will print the version of the library per the number of EVSEs (or network interfaces) that we will start the slac for.

A better place for it is here, which is just spawned once: https://github.com/SwitchEV/pyslac/blob/master/pyslac/session.py#L834

2022-09-20 14:23 UTC, mdwcrft commented on pyslac/session.py
> +        )
Thanks, I've moved it to the `SlacSessionController`

2022-10-04 07:41 UTC, santiagosalamandri approved these changes

2022-10-04 07:48 UTC, merged

2022-10-04 09:01 UTC, RoastVeg commented
Ported to RSlac in https://github.com/SwitchEV/rslac/commit/5c4eafa7974b43cf575ef922586bed20cc5f5e2c