Feat/improve logging
SwitchEV/pyslac pull request #38
Opened 2022-10-28 10:40 UTC by santiagosalamandri

This PR adds/fixes:

- Remove unneeded empty lines
- Show successful matching as INFO
- Change INFO for SET_KEY finished
- Change INFO for Link established
- Add summary after CM_ATTEN_CHAR with nr of soundings it is based on

2022-11-22 17:31 UTC, tropxy requested changes

2022-11-23 10:07 UTC, santiagosalamandri commented on pyslac/session.py
> +                logger.info("Matching ongoing...")
Done.

2022-11-23 10:07 UTC, santiagosalamandri commented on pyslac/session.py
> +                logger.info("PEV-EVSE MATCHED Successfully, Link Established")
Done.

2022-11-28 23:09 UTC, tropxy approved these changes

2022-11-28 23:09 UTC, tropxy commented
just needs a rebase, @santiagosalamandri

2022-11-29 09:26 UTC, merged